service: default
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 2
    memory_gb: 16
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 app:server




